### ISSUE TITLE
请求返回错误x-rpcx-errormessage是乱码

### ISSUE THREAD

**Issue by pengshaomin** [rpcxio/rpcx-gateway#10]
![image](https://user-images.githubusercontent.com/17870116/71442601-853dd180-2741-11ea-97ab-a0b48aa9ba44.png)

**Comment by smallnest** [comment]
有可能rpcx service返回的错误就是二进制的，抓包看一看

**Comment by pengshaomin** [comment]
通过gateway请求的  中文显示乱码,英文正常

**Comment by smallnest** [comment]
rpcx service返回什么错误gateway就返回什么错误。

所以你需要检查是不是rpcx service本身就返回乱码。

可以通过抓包或者绕过gateway直接访问rpcx service,看看错误信息是否正常。

如果只凭现有提供的信息，只能断定rpcx service返回的字符串是乱码字符串。

**Comment by pengshaomin** [comment]
暂时搞不懂
