### ISSUE TITLE
geteway只有客户端例子，服务端怎么写呢？服务端监听的是8872，但是http请求的是9981端口

### ISSUE THREAD

**Issue by tomener** [rpcxio/rpcx-gateway#14]
geteway和agent只有客户端例子，服务端怎么写呢？我看server里面写的和一般的服务端没什么区别，服务端监听的是8872，但是http请求的是9981端口，这样也可以？

怎样启动geteway，能有个教程就好了，对于新手有点懵，后面看见了cmd下面的代码才知道怎么回事儿了

**Comment by smallnest** [comment]
需要补充一个部署图。

**Comment by ztg1** [comment]
新手 表示运行不来的这个案例 求求大佬指点

**Comment by smallnest** [comment]
这个例子指你需要部署一个rpcx-gateway程序，通过它转发请求到后端的服务器。

不建议你这样使用，除非你开发一个自己的rpcx-gateway集群。

你可以通过http invoke的方式访问rpcx服务，你可以看http invoke的例子。对于非Go的其它编程语言，这是推荐的方式。

**Comment by ztg1** [comment]
谢谢大佬的提醒  我已经跑起来  1 先运行一个之前案例里一个rpc的服务;  2 运行这个gateway.go ; 3 通过http或者运行这个例子的examples下其它语言client即可看到效果；

**Comment by ztg1** [comment]
谢谢大佬的提醒  我已经跑起来  1 先运行一个之前案例里一个rpc的服务;  2 运行这个gateway.go ; 3 通过http或者运行这个例子的examples下其它语言client即可看到效果；
