### ISSUE TITLE
cmd/gateway.go registry参数在不同注册方式上怎么写，能给一个例子吗？目前只看见一个peer2peer

### ISSUE THREAD

**Issue by tomener** [rpcxio/rpcx-gateway#15]
cmd/gateway.go registry参数在不同注册方式上怎么写，能给一个例子吗？目前只看见一个peer2peer

**Comment by smallnest** [comment]
参考

https://github.com/rpcx-ecosystem/rpcx-examples3/tree/master/registry

或文档

https://doc.rpcx.io/part2/registry.html
