### ISSUE TITLE
当前版本依赖的rpcx-etcd版本中的etcd版本不存在

### ISSUE THREAD

**Issue by mybestcool** [rpcxio/rpcx-gateway#21]
依赖
github.com/rpcxio/rpcx-etcd v0.0.0-20201229103411-8317fc934fbb
而rpcx-etcd 这个版本需要go.etcd.io/etcd@v3.4.14版本，
然后使用了goproxy.io代理后查看etcd所有版本go list -m -json -versions go.etcd.io/etcd@latest，缺少3.4.14版本。
{
        "Path": "go.etcd.io/etcd",
        "Version": "v3.3.25+incompatible",
        "Versions": [
                "v0.1.0",
                "v0.1.1",
                "v0.1.2",
                "v0.2.0-rc0",
                "v0.2.0-rc1",
                "v0.2.0-rc2",
                "v0.2.0-rc3",
                "v0.2.0-rc4",
                "v0.2.0",
                "v0.3.0",
                "v0.4.0",
                "v0.4.1",
                "v0.4.2",
                "v0.4.3",
                "v0.4.4",
                "v0.4.5",
                "v0.4.6",
                "v0.4.7",
                "v0.4.8",
                "v0.4.9",
                "v0.5.0-alpha.0",
                "v0.5.0-alpha.1",
                "v0.5.0-alpha.2",
                "v0.5.0-alpha.3",
                "v0.5.0-alpha.4",
                "v0.5.0-alpha.5",
                "v2.0.0-rc.1+incompatible",
                "v2.0.0+incompatible",
                "v2.0.1+incompatible",
                "v2.0.2+incompatible",
                "v2.0.3+incompatible",
                "v2.0.4+incompatible",
                "v2.0.5+incompatible",
                "v2.0.6+incompatible",
                "v2.0.7+incompatible",
                "v2.0.8+incompatible",
                "v2.0.9+incompatible",
                "v2.0.10+incompatible",
                "v2.0.11+incompatible",
                "v2.0.12+incompatible",
                "v2.0.13+incompatible",
                "v2.1.0-alpha.0+incompatible",
                "v2.1.0-alpha.1+incompatible",
                "v2.1.0-rc.0+incompatible",
                "v2.1.0+incompatible",
                "v2.1.1+incompatible",
                "v2.1.2+incompatible",
                "v2.1.3+incompatible",
                "v2.2.0-alpha.0+incompatible",
                "v2.2.0-alpha.1+incompatible",
                "v2.2.0-rc.0+incompatible",
                "v2.2.0+incompatible",
                "v2.2.1+incompatible",
                "v2.2.2+incompatible",
                "v2.2.3+incompatible",
                "v2.2.4+incompatible",
                "v2.2.5+incompatible",
                "v2.3.0-alpha.0+incompatible",
                "v2.3.0-alpha.1+incompatible",
                "v2.3.0+incompatible",
                "v2.3.1+incompatible",
                "v2.3.2+incompatible",
                "v2.3.3+incompatible",
                "v2.3.4+incompatible",
                "v2.3.5+incompatible",
                "v2.3.6+incompatible",
                "v2.3.7+incompatible",
                "v2.3.8+incompatible",
                "v3.0.0-beta.0+incompatible",
                "v3.0.0+incompatible",
                "v3.0.1+incompatible",
                "v3.0.2+incompatible",
                "v3.0.3+incompatible",
                "v3.0.4+incompatible",
                "v3.0.5+incompatible",
                "v3.0.6+incompatible",
                "v3.0.7+incompatible",
                "v3.0.8+incompatible",
                "v3.0.9+incompatible",
                "v3.0.10+incompatible",
                "v3.0.11+incompatible",
                "v3.0.12+incompatible",
                "v3.0.13+incompatible",
                "v3.0.14+incompatible",
                "v3.0.15+incompatible",
                "v3.0.16+incompatible",
                "v3.0.17+incompatible",
                "v3.1.0-alpha.0+incompatible",
                "v3.1.0-alpha.1+incompatible",
                "v3.1.0-rc.0+incompatible",
                "v3.1.0-rc.1+incompatible",
                "v3.1.0+incompatible",
                "v3.1.1+incompatible",
                "v3.1.2+incompatible",
                "v3.1.3+incompatible",
                "v3.1.4+incompatible",
                "v3.1.5+incompatible",
                "v3.1.6+incompatible",
                "v3.1.7+incompatible",
                "v3.1.8+incompatible",
                "v3.1.9+incompatible",
                "v3.1.10+incompatible",
                "v3.1.11+incompatible",
                "v3.1.12+incompatible",
                "v3.1.13+incompatible",
                "v3.1.14+incompatible",
                "v3.1.15+incompatible",
                "v3.1.16+incompatible",
                "v3.1.17+incompatible",
                "v3.1.18+incompatible",
                "v3.1.19+incompatible",
                "v3.1.20+incompatible",
                "v3.2.0-rc.0+incompatible",
                "v3.2.0-rc.1+incompatible",
                "v3.2.0+incompatible",
                "v3.2.1+incompatible",
                "v3.2.2+incompatible",
                "v3.2.3+incompatible",
                "v3.2.4+incompatible",
                "v3.2.5+incompatible",
                "v3.2.6+incompatible",
                "v3.2.7+incompatible",
                "v3.2.8+incompatible",
                "v3.2.9+incompatible",
                "v3.2.10+incompatible",
                "v3.2.11+incompatible",
                "v3.2.12+incompatible",
                "v3.2.13+incompatible",
                "v3.2.14+incompatible",
                "v3.2.15+incompatible",
                "v3.2.16+incompatible",
                "v3.2.17+incompatible",
                "v3.2.18+incompatible",
                "v3.2.19+incompatible",
                "v3.2.20+incompatible",
                "v3.2.21+incompatible",
                "v3.2.22+incompatible",
                "v3.2.23+incompatible",
                "v3.2.24+incompatible",
                "v3.2.25+incompatible",
                "v3.2.26+incompatible",
                "v3.2.27+incompatible",
                "v3.2.28+incompatible",
                "v3.2.29+incompatible",
                "v3.2.30+incompatible",
                "v3.2.31+incompatible",
                "v3.3.0-rc.0+incompatible",
                "v3.3.0-rc.1+incompatible",
                "v3.3.0-rc.2+incompatible",
                "v3.3.0-rc.3+incompatible",
                "v3.3.0-rc.4+incompatible",
                "v3.3.0+incompatible",
                "v3.3.1+incompatible",
                "v3.3.2+incompatible",
                "v3.3.3+incompatible",
                "v3.3.4+incompatible",
                "v3.3.5+incompatible",
                "v3.3.6+incompatible",
                "v3.3.7+incompatible",
                "v3.3.8+incompatible",
                "v3.3.9+incompatible",
                "v3.3.10+incompatible",
                "v3.3.11+incompatible",
                "v3.3.12+incompatible",
                "v3.3.13+incompatible",
                "v3.3.15+incompatible",
                "v3.3.16+incompatible",
                "v3.3.17+incompatible",
                "v3.3.18+incompatible",
                "v3.3.19+incompatible",
                "v3.3.20+incompatible",
                "v3.3.21+incompatible",
                "v3.3.22+incompatible",
                "v3.3.24+incompatible",
                "v3.3.25+incompatible"
        ],
        "Time": "2020-08-24T19:33:27Z",
        "GoMod": "C:\\GoPath\\pkg\\mod\\cache\\download\\go.etcd.io\\etcd\\@v\\v3.3.25+incompatible.mod"
}

**Comment by smallnest** [comment]
可以更新最新的rpcx-etcd看看

**Comment by mybestcool** [comment]
使用了最新的rpcx-etcd@v0.0.0-20210309015740-324bede3ab7c，
问题是当前最新版本rpcx-gateway@v0.0.0-20201229104047-37b78692ee7f依赖的github.com/rpcxio/rpcx-etcd v0.0.0-20201229103411-8317fc934fbb，并不是最新版本，这个版本rpcx-etcd依赖go.etcd.io/etcd不是最新版本

**Comment by smallnest** [comment]
更新最新的rpcx-gateway
