### ISSUE TITLE
go mod 下载包，老是提示etcd包版本问题

### ISSUE THREAD

**Issue by huzhao37** [rpcxio/rpcx-gateway#22]
![image](https://user-images.githubusercontent.com/17268060/117923458-a0a18080-b326-11eb-9182-4ddcaff8e1b7.png)

**Comment by huzhao37** [comment]
![image](https://user-images.githubusercontent.com/17268060/117925547-004d5b00-b32a-11eb-80d2-ac68eae92802.png)
试着将etcd相关版本更新后就没问题了。。。etcd mod管理老大难了。。

**Comment by smallnest** [comment]
你再拉一下试试

**Comment by huzhao37** [comment]
可以了，感谢！
![image](https://user-images.githubusercontent.com/17268060/117929153-07c33300-b32f-11eb-9295-4f9812d19605.png)
