### ISSUE TITLE
getway 到 后端rpcx服务，断断续续

### ISSUE THREAD

**Issue by syklinux** [rpcxio/rpcx-gateway#23]
请求同一个rpcx服务，第一下好的，第二下就会报错，一直循环
报错信息：
failed to dial server: dial tcp: address /rpc/xxxx: missing port in address

采用 etcd v3，单etcd节点，
后端rpcx服务提示：client has closed this connection

**Comment by smallnest** [comment]
服务端注册有问题，把服务端的配置代码发一下

**Comment by syklinux** [comment]
![image](https://user-images.githubusercontent.com/22145091/123516665-d11f5d00-d6cf-11eb-9458-804eb6dc8d00.png)

AddRegistryPlugin(s, ips[0])
s.Plugins.Add(traceP)

if err = s.RegisterName("OpsUser", new(rpc.Rpc), ""); err != nil {
log.Fatalf("server Register err:", err)
}
go func() {
if err = s.Serve("tcp", ips[0]+":"+util.Port); err != nil {
	     panic(err)
}
}()

func AddRegistryPlugin(s *server.Server, ip string) {
	conf := config.EtcdConf()
	option := &store.Config{}
	if conf.Username != "" {
		option = &store.Config{
			Username: conf.Username,
			Password: conf.Password,
		}
	}
	r := &serverplugin.EtcdV3RegisterPlugin{
		ServiceAddress: "tcp@" + ip + ":" + Port,
		EtcdServers:    conf.EtcdAddr,
		BasePath:       conf.BasePath,
		Metrics:        metrics.NewRegistry(),
		UpdateInterval: time.Minute,
		Options:        option,
	}
	err := r.Start()
	if err != nil {
		log.Fatalf(err.Error())
	}
	s.Plugins.Add(r)
}
