### ISSUE TITLE
运行'cmd/gateway.go'报错

### ISSUE THREAD

**Issue by kidnet** [rpcxio/rpcx-gateway#7]
运行 cmd/gateway.go 后报错如下：
`./gateway.go:56:10: undefined: client.NewZookeeperDiscoveryTemplate`
`./gateway.go:58:10: undefined: client.NewEtcdDiscoveryTemplate`
`./gateway.go:60:10: undefined: client.NewConsulDiscoveryTemplate`

**Comment by smallnest** [comment]
see readme of rpcx and use build tags:

```
-tags "reuseport quic kcp zookeeper etcd consul ping rudp utp"
```
