### ISSUE TITLE
go build error

### ISSUE THREAD

**Issue by zhengchengbin610** [rpcxio/rpcx-gateway#8]
我下载后直接go build 出现以下错误，有一些方法没有定义？请问是我用错了吗？能指导一下吗？
![image](https://user-images.githubusercontent.com/26518131/60065407-6761c680-9736-11e9-9b77-3e1ce1378f8b.png)

**Comment by smallnest** [comment]
更新你的rpcx。


根据错误提示，找到对应的struct定义，看看有没有这个方法， 和github的最新的文件对比一下
